### ISSUE TITLE
Significantly greater load time due to warnings from using deprecated methods

### ISSUE THREAD

**Issue by monochrome-blue** [haveric/RecipeManager2#80]
I noticed when I updated my server earlier today to the latest paper-1286 (for version 1.12.2), RecipeManager has taken significantly longer to load, due to the warnings displayed in console for using deprecated methods. I'm not too sure if the same thing occurs on Spigot either, but I'm assuming it would? The warning looks like this:

```
[17:40:01 WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[17:40:01 WARN]:        at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:26)
[17:40:01 WARN]:        at haveric.recipeManager.recipes.CraftRecipe.toBukkitRecipe(CraftRecipe.java:286)
[17:40:01 WARN]:        at haveric.recipeManager.recipes.CraftRecipe.toBukkitRecipe(CraftRecipe.java:26)
[17:40:01 WARN]:        at haveric.recipeManager.recipes.BaseRecipe.getBukkitRecipe(BaseRecipe.java:110)
[17:40:01 WARN]:        at haveric.recipeManager.Recipes.registerRecipe(Recipes.java:354)
[17:40:01 WARN]:        at haveric.recipeManager.RecipeRegistrator.registerRecipesToServer(RecipeRegistrator.java:86)
[17:40:01 WARN]:        at haveric.recipeManager.RecipeProcessor$1.run(RecipeProcessor.java:169)
[17:40:01 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
[17:40:01 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[17:40:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833)
[17:40:01 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426)
[17:40:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767)
[17:40:01 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665)
[17:40:01 WARN]:        at java.lang.Thread.run(Thread.java:748)

```

and seems to be shown for every recipe. This increases load times significantly, taking about 20 seconds to load 43 recipes. The plugin works just great though otherwise- just that loading recipes takes a while.

**Comment by haveric** [comment]
Thanks. It seems only paper is spitting out those errors, but that is definitely concerning with how long it takes. This should be pretty easy to fix though, so I'll definitely look into it as soon as i can.
