### ISSUE TITLE
Task #240 generated an exception

### ISSUE THREAD

**Issue by Bufhimat** [haveric/RecipeManager2#87]
Getting this error when starting the server

Ubuntu server 18.04
MC1.14.4
paper-173

[13:55:45 WARN]: [RecipeManager] Task #240 for RecipeManager v2.16.1 generated an exception
java.lang.NullPointerException: null
        at haveric.recipeManager.Files.createNameIndex(Files.java:509) ~[?:?]
        at haveric.recipeManager.Files.<init>(Files.java:77) ~[?:?]
        at haveric.recipeManager.Files.reload(Files.java:65) ~[?:?]
        at haveric.recipeManager.RecipeManager.reload(RecipeManager.java:181) ~[?:?]
        at haveric.recipeManager.RecipeManager.onEnablePost(RecipeManager.java:127) ~[?:?]
        at haveric.recipeManager.RecipeManager.access$000(RecipeManager.java:42) ~[?:?]
        at haveric.recipeManager.RecipeManager$1.run(RecipeManager.java:106) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-173]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-173]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-173]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-173]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-173]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-173]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by haveric** [comment]
I'm not able to replicate this on paper-173. Do you have any other plugins running (specifically any that have custom enchantments)?

**Comment by Bufhimat** [comment]
Not sure what all changed between this post and resolution, but cleared before isolation.
I did have other plugins. I removed them all and RecipeManager worked. Then I loaded mods back in a few at a time but never recreated the issue, and I have been able to create recipes.

**Comment by haveric** [comment]
The above code would only fire if the 'name index.html' file doesn't exist. Can you try deleting it and testing again?
