### ISSUE TITLE
1.15.2 cannot @remove vanilla recipes and @restrict gives an error

### ISSUE THREAD

**Issue by Ilmatarnyymi** [haveric/RecipeManager2#92]
craft
@remove

diamond
diamond
stick
= diamond_sword

this recipe was extracted with /rmextract but doesnt remove the recipe, using paper-80

recipe goes through with no errors but i can still craft the sword.

-

craft
@restrict

diamond
diamond
stick
= diamond_sword

[01:54:38] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[01:54:38] [Server thread/INFO]: Loaded 6 recipes
[01:54:39] [Craft Scheduler Thread - 242/INFO]: [RecipeManager] Loading all recipes...
[01:54:39] [Craft Scheduler Thread - 242/INFO]: [RecipeManager] Error while reading recipe files! (null)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: java.lang.NullPointerException
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at haveric.recipeManagerCommon.util.RMCUtil.trimExactQuotes(RMCUtil.java:132)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at haveric.recipeManager.flag.flags.recipe.FlagRestrict.onParse(FlagRestrict.java:62)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at haveric.recipeManager.flag.Flags.parseFlag(Flags.java:137)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at haveric.recipeManager.recipes.RecipeFileReader.parseFlags(RecipeFileReader.java:160)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at haveric.recipeManager.recipes.craft.CraftRecipeParser.parseRecipe(CraftRecipeParser.java:40)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at haveric.recipeManager.recipes.RecipeFileParser.parseFile(RecipeFileParser.java:53)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at haveric.recipeManager.RecipeProcessor.run(RecipeProcessor.java:102)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[01:54:39] [Craft Scheduler Thread - 242/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[01:54:39] [Craft Scheduler Thread - 242/INFO]: [RecipeManager] If you're using the latest version you should report this error at: https://dev.bukkit.org/projects/recipemanager/issues/create
[01:54:39] [Craft Scheduler Thread - 242/INFO]: [RecipeManager] Parsed 9 recipes from 10 files without errors, elapsed time 0.005 seconds.

**Comment by haveric** [comment]
RecipeManager does not yet have 1.15 support. I have most of it ready to go, but have not had the time to do the testing needed to launch it and verify functionality.

**Comment by Ilmatarnyymi** [comment]
good to hear. old version works for most parts and the parts that dont i can usually work around them.

**Comment by haveric** [comment]
Forgot to post here right away, but there is a new dev build that should have support for 1.15 that is available on [discord](https://discordapp.com/invite/3JY9JC3). If you get a chance, please test it out and let me know if you run into any issues.

**Comment by haveric** [comment]
This should be fixed in the latest release: v2.19.0

Please create a new ticket if you're still experiencing any issues after updating.
